123-actualizado/articulo/urls.py
from django.urls import path
from .views import  listar_articulos_por_categoria, listar_articulos_por_categorias, listar_categorias, ArtListView, ArtCreateView, AllArticlesView, AllCategoriaView, CategoryCreateView, ArtDetailView, ArtUpdateView, ArtDeleteView

app_name="articulos"

urlpatterns = [
    path('', ArtListView.as_view(), name="home"),
    path('create/', ArtCreateView.as_view(), name="create"),
    path('all-articles/', AllArticlesView.as_view(), name="all_articles"),
    path('all-category/', AllCategoriaView.as_view(), name="all_category"),
    path('create-category/', CategoryCreateView.as_view(), name="create_category"),
    path('Article/<int:post_id>/', ArtDetailView.as_view(), name="detail"),
    path('<int:pk>/update/', ArtUpdateView.as_view(), name="update"),
    path('<int:pk>/delete/', ArtDeleteView.as_view(), name="delete"),

    path('categorias/', listar_categorias.as_view(), name='listar_categorias'),
    path('categoria/<int:categoria_id>/', listar_articulos_por_categorias.as_view(), name='listar_articulos_por_categorias'),
]

123-actualizado/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from articulo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='homee'),
    path('', include('articulo.urls')),
    path('articulos/', include('articulo.urls', namespace='articulos-namespace'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

123-actualizado/articulo/models.py
from django.db import models
import datetime
from django.db.models.signals import post_delete
from django.dispatch import receiver

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Articles(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    image = models.ImageField(upload_to='articles/images')
    date_published = models.DateField(default=datetime.date.today)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.title

# Señal para eliminar el archivo de imagen cuando se elimina un artículo
@receiver(post_delete, sender=Articles)
def delete_article_image(sender, instance, **kwargs):
    # Eliminar el archivo de imagen cuando se elimina el artículo
    instance.image.delete(False)

123-actualizado/articulo/forms.py
from django import forms
from .models import Articles, Category

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Articles
        fields = ('title', 'content', 'image', 'date_published', 'category')
        labels = {
            'title': 'Título',
            'content': 'Contenido',
            'image': 'Imagen',
            'date_published': 'Fecha de Publicación',
            'category': 'Categoría',
        }

    def clean_title(self):
        title = self.cleaned_data['title']
        if not title.strip():
            raise forms.ValidationError("El título no puede estar vacío.")
        return title

    def clean_content(self):
        content = self.cleaned_data['content']
        if not content.strip():
            raise forms.ValidationError("El contenido no puede estar vacío.")
        return content

    # Puedes agregar más validaciones según tus necesidades

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('name',)
        labels = {
            'name': 'Nombre de la Categoría',
        }

    def clean_name(self):
        name = self.cleaned_data['name']
        if not name.strip():
            raise forms.ValidationError("El nombre de la categoría no puede estar vacío.")
        return name

123-actualizado/articulo/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib import messages
from django.views.generic import View, UpdateView, DeleteView
from .forms import ArticleForm, CategoryForm
from .models import Articles, Category
from django.urls import reverse_lazy


# Create your views here.
def home(request):
    articles = Articles.objects.order_by('-date_published')[:3]
    return render(request, 'home.html', {'articles': articles})


# para crear categorias
class CategoryCreateView(View):
    def get(self, request, *args, **kwargs):
        form = CategoryForm()
        context = {
            'form': form
        }
        return render(request, 'profile/articles/category_create.html', context)

    def post(self, request, *args, **kwargs):
        if request.method == "POST":
            form = CategoryForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('articulos:home')

        context = {}
        return render(request, 'profile/articles/category_create.html', context)




# mostrar todos los articulos desde nav articulos
class AllArticlesView(View):
    def get(self, request, *args, **kwargs):
        articles = Articles.objects.all()
        context = {
            'articles': articles  
        }
        return render(request, 'profile/articles/all_articles.html', context)





# para articulos CRUD
class ArtListView(View):
    def get(self, request, *args, **kwargs):
        articles = Articles.objects.order_by('-date_published')[:3]
        context = {
            'articles': articles
        }
        return render(request, 'home.html', context)


class ArtCreateView(View):
    def get(self, request, *args, **kwargs):
        form = ArticleForm(initial={'category':1})
        context = {
            'form': form
        }
        return render(request, 'profile/articles/Art_create.html', context)

    def post(self, request, *args, **kwargs):
        if request.method == "POST":
            form = ArticleForm(request.POST, request.FILES)
            if form.is_valid():
                title = form.cleaned_data.get('title')
                content = form.cleaned_data.get('content')
                image = form.cleaned_data.get('image')
                date_published = form.cleaned_data.get('date_published')
                category = form.cleaned_data.get('category')

                p, created = Articles.objects.get_or_create(title=title, content=content, image=image, date_published=date_published, category=category)
                p.save()
                return redirect('articulos:home')

        context = {}
        return render(request, 'profile/articles/Art_create.html', context)


class ArtDetailView(View):
    def get(self, request, post_id, *args, **kwargs):
        article = get_object_or_404(Articles, pk=post_id)
        context = {
            'article': article
        }
        return render(request, 'profile/articles/Art_detail.html', context)


class ArtUpdateView(UpdateView):
    model = Articles
    form_class = ArticleForm
    template_name = 'profile/articles/Art_update.html'

    def form_valid(self, form):
        messages.success(self.request, 'Los cambios se han guardado exitosamente.')
        response = super().form_valid(form)
        return response

    def get_success_url(self):
        pk = self.kwargs['pk']
        return reverse_lazy('articulos:detail', kwargs={'post_id': pk})



class ArtDeleteView(DeleteView):
    model = Articles
    template_name = 'profile/articles/Art_delete.html'
    success_url = reverse_lazy('articulos:home')


#Mostrar las categoria
class AllCategoriaView(View):
    def get(self, request, *args, **kwargs):
        categorys = Category.objects.all()
        context = {
            'categorys': categorys
        }
        return render(request, 'category/all_category.html', context)
    

def listar_categorias(request):
    categorias = Category.objects.all()
    return render(request, 'listar_categorias.html', {'categorias': categorias})

def listar_articulos_por_categoria(request, categoria_id):
    categoria = Category.objects.get(pk=categoria_id)
    articulos = Articles.objects.filter(categoria=categoria)
    return render(request, 'listar_articulos_por_categoria.html', {'categoria': categoria, 'articulos': articulos})

class listar_categorias(View):
    def get(self, request, *args, **kwargs):
        categorys = Category.objects.all()
        context = {
            'categorys': categorys
        }
        return render(request, 'category/all_category.html', context)
    
class listar_articulos_por_categorias(View):
    def get(self, request, *args, **kwargs):
        categorys = Category.objects.all()
        articles = Articles.objects.all()
        context = {
            'articles': articles
         }
        return render(request, 'category/all_category.html', context)

123-actualizado/articulo/templates/category/Listar_categorias.html
<!DOCTYPE html>
<html>
<head>
    <title>Listado de Categorías</title>
</head>
<body>
    <h1>Listado de Categorías</h1>
    <ul>
        {% for categoria in categorias %}
        <li><a href="{% url 'listar_articulos_por_categoria' categoria.id %}">{{ categoria.nombre }}</a></li>
        {% endfor %}
    </ul>
</body>
</html>

123-actualizado/articulo/templates/category/all_category.html
{% extends 'layout.html' %}

{% block content %}
<div class="text-center">
    <h1>Todos las categorias</h1>
    <div class="row row-cols-1 row-cols-md-3 g-4">
        <ol class="list-group list-group-numbered">
            {% for category in categorys %}
            <li class="list-group-item d-flex justify-content-between align-items-start">
                <div class="ms-2 me-auto">
                    <div class="fw-bold">{{ category.name }}</div>
                    {{ category.content }}
                </div>
                <span class="badge bg-primary rounded-pill">{{ category.count }}</span>
            </li>
            {% endfor %}
        </ol>
    </div>
</div>
{% endblock %}

123-actualizado/articulo/templates/home.html
{% extends 'layout.html' %}

{% block content %}

<!-- Porfolio Section -->
<div class="row my-4 text-center">

    <h3>Red Salud Popular Carrillo</h3>
    <p>🌱"NO'OXONEC Algodón de Frontera'Campaña QARTAGO´Q</p>
  
    {% for article in articles %}
    <div class="col-md-4 p-4">
      <div class="card bg-dark text-white card-project">
        <img src="{{article.image.url }}" class="card-img-top" />
  
        <div class="card-body">
  
          <h2>{{ article.title }}</h2>

          <p>{{ article.content|striptags |truncatechars:100 }}</p>

          <div class="btn-group" role="group" aria-label="Basic mixed styles example">
            <a href="{% url 'articulos:detail' article.id %}" class="btn btn-success">Seguir Leyendo</a>
            <a href="{% url 'articulos:update' article.id %}" class="btn btn-warning ms-2">Editar</a>
            <a href="{% url 'articulos:delete' article.id %}" class="btn btn-danger ms-2">Eliminar</a>
          </div>

        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  
  
  {% endblock %}

123-actualizado/articulo/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PortalPost</title>
    {% comment %} <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"> {% endcomment %}
     <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    
    <link rel="stylesheet" href="{% static 'main.css' %}">
</head>
<body class="color-body text-white">

    {% include 'partials/navbar.html' %}

    <div class="container p-4">
        {% block content %}
        {% endblock %}
    </div>

    <footer>footer</footer>


     <!-- Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</body>
</html>

123-actualizado/articulo/templates/partials/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand fw-bold fst-italic" href="/">PortalPost</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'articulos:all_articles'%}">Articulos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'articulos:all_category'%}">Categorías</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="#">Acerca de</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="#">Contacto</a>
                </li>

                <!-- Menú desplegable "Mi Perfil" -->
                <li class="nav-item dropdown">
                    <a class="nav-link active dropdown-toggle" href="#" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                        {% comment %} <img src="{% static 'images/perfil-default.png' %}" alt="Mi Perfil" class="profile-image"> {% endcomment %}
                        Perfil
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                      <li><a class="dropdown-item" href="#">Ver Perfil</a></li>
                      <li><a class="dropdown-item" href="{% url 'articulos:create' %}">Publicar Articulos</a></li>
                      <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>

            </ul>
        </div>
    </div>
</nav>

  

123-actualizado/articulo/templates/profile/articles/Art_create.html
{% extends 'layout.html' %}

{% block content %}
  <h1>Crear Artículo</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar Artículo</button>
  </form>

  <form method="get" action="{% url 'articulos:create_category' %}">
    {% csrf_token %}
    <button type="submit">Crear Categoría</button>
  </form>
  
{% endblock %} 

123-actualizado/articulo/templates/profile/articles/Art_delete.html
{% extends 'layout.html' %}

{% block content %}
  <h1>Eliminar Artículo</h1>
  <p>¿Estás seguro de que deseas eliminar el siguiente artículo?</p>
  <h2>{{ article.title }}</h2>
  <p>{{ article.content }}</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Eliminar</button>
  </form>
{% endblock %}

123-actualizado/articulo/templates/profile/articles/Art_detail.html
{% extends 'layout.html' %}

{% block content %}

{% if messages %}
    {% for message in messages %}
        {% if message.tags == 'success' %}
            <div class="alert alert-success" role="alert">
                <h4 class="alert-heading">¡Bien hecho!</h4>
                <p>{{ message }}</p>
                <hr>
                <p class="mb-0">¡Excelente trabajo!</p>
            </div>
        {% endif %}
    {% endfor %}
{% endif %}





<div class="text-center">

    <h1>{{article.title}}</h1>
    <h2 class="my-2 h5 text-muted">{{article.date_published}}</h2>
  
    <img src="{{article.image.url}}" alt="{{article.title}}" class="img-fluid">
  
  
    <div class="my-4">
  
    {{article.content|safe}}
    </div>
  </div>

{% endblock %}

123-actualizado/articulo/templates/profile/articles/Art_list.html
{% comment %} {% extends 'layout.html' %}

{% block content %}
    <h1>Listado de Artículos</h1>

    <ul>
        {% for article in articles %}
            <li>
                <h2>{{ article.title }}</h2>
                <p>{{ article.content }}</p>
                <!-- Agrega más detalles o campos del artículo aquí, si es necesario -->
            </li>
        {% endfor %}
    </ul>
{% endblock %} {% endcomment %}

{% extends 'layout.html' %}

{% block content %}
  <h1>Listado de Artículos</h1>
  <ul>
    {% for article in articles %}
      <li>
        <h2><a href="{% url 'blog:detail' article.pk %}">{{ article.title }}</a></h2>
        <p>{{ article.content }}</p>
        <!-- Agrega más detalles o campos del artículo aquí, si es necesario -->
      </li>
    {% endfor %}
  </ul>
{% endblock %}

123-actualizado/articulo/templates/profile/articles/Art_update.html
{% extends 'layout.html' %}

{% block content %}
  <h1>Actualizar Artículo</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar Cambios</button>
  </form>
{% endblock %}

123-actualizado/articulo/templates/profile/articles/Category.html
<!-- categoria.html -->
{% extends 'layout.html' %} 
<!DOCTYPE html>
<html>
<head>
    <title>Listado de Categorías</title>
</head>
<body>

<h1>Listado de Categorías</h1>

<ul>
  {% for categoria in categorias %}
    <li>{{ categoria.nombre }}</li>
  {% endfor %}
</ul>

</body>
</html>

123-actualizado/articulo/templates/profile/articles/all_articles.html
{% extends 'layout.html' %}

{% block content %}
<div class="text-center">
    <h1>Todos los Artículos</h1>
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for article in articles %}
        <div class="col">
            <!-- Agregar un estilo de fondo a la tarjeta -->
            <div class="card h-100" class="bg-dark">
                <img src="{{ article.image.url }}" class="card-img-top" alt="{{ article.title }}" style="max-height: 150px; object-fit: cover;">
                <div class="card-body">
                    <h6 class="card-subtitle mb-2 text-muted">{{ article.date_published|date:'M d Y' }}</h6>
                    <h5 class="text-dark" class="card-title" >{{ article.title }}</h5>
                    <p class="text-dark" class="card-text">{{ article.content|striptags |truncatechars:100  }}</p>
                        <div class="btn-group" role="group" aria-label="Basic mixed styles example">
                            <a href="{% url 'articulos:detail' article.id %}" class="btn btn-success">Seguir Leyendo</a>
                            <a href="{% url 'articulos:update' article.id %}" class="btn btn-warning ms-2">Editar</a>
                            <a href="{% url 'articulos:delete' article.id %}" class="btn btn-danger ms-2">Eliminar</a>
                        </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

123-actualizado/articulo/templates/profile/articles/category_create.html
{% extends 'layout.html' %}

{% block content %}
  <h1>Crear Categoría</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar Categoría</button>
  </form>
{% endblock %}

123-actualizado/articulo/templates/profile/articles/listar_articulos_por_categoria.html
<!DOCTYPE html>
<html>
<head>
    <title>{{ categoria.nombre }}</title>
</head>
<body>
    <h1>{{ categoria.nombre }}</h1>
    <ul>
        {% for articulo in articulos %}
        <li>
            <h2>{{ articulo.titulo }}</h2>
            <p>{{ articulo.contenido }}</p>
        </li>
        {% endfor %}
    </ul>
</body>
</html>